<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261006100959 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'File de construction des bâtiments, usines de robots et de nanites';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE building_queue_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, paid_metal DOUBLE PRECISION NOT NULL, paid_crystal DOUBLE PRECISION NOT NULL, paid_deuterium DOUBLE PRECISION NOT NULL, target_level INT NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, event_id INT DEFAULT NULL, planet_id INT NOT NULL, type_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9403026D71F7E88B ON building_queue_item (event_id)');
        $this->addSql('CREATE UNIQUE INDEX building_queue_item_planet_unique ON building_queue_item (planet_id)');
        $this->addSql('CREATE INDEX IDX_9403026DC54C8C93 ON building_queue_item (type_id)');
        $this->addSql('CREATE TABLE building_queue_item_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, extra_data JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_3d45122812d10c4b801d474107db4fac_idx ON building_queue_item_audit (type)');
        $this->addSql('CREATE INDEX object_id_3d45122812d10c4b801d474107db4fac_idx ON building_queue_item_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_3d45122812d10c4b801d474107db4fac_idx ON building_queue_item_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_3d45122812d10c4b801d474107db4fac_idx ON building_queue_item_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_3d45122812d10c4b801d474107db4fac_idx ON building_queue_item_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_3d45122812d10c4b801d474107db4fac_idx ON building_queue_item_audit (created_at)');
        $this->addSql('ALTER TABLE building_queue_item ADD CONSTRAINT FK_9403026D71F7E88B FOREIGN KEY (event_id) REFERENCES scheduled_event (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE building_queue_item ADD CONSTRAINT FK_9403026DA25E9820 FOREIGN KEY (planet_id) REFERENCES planet (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE building_queue_item ADD CONSTRAINT FK_9403026DC54C8C93 FOREIGN KEY (type_id) REFERENCES building_type (id) NOT DEFERRABLE');
        // Usines (§4.3) : accélèrent les constructions ; paramètres OGame, réglables dans le panneau
        $this->addSql('INSERT INTO building_type (code, name, effect, base_cost_metal, base_cost_crystal, base_cost_deuterium, cost_factor, effect_base, effect_growth, energy_consumption, deuterium_consumption, temperature_base, temperature_coefficient, sort_order, description) VALUES (\'robot_factory\', \'Usine de robots\', \'robot_factory\', 400, 120, 200, 2, 0, 1, 0, 0, 1, 0, 90, \'Accélère la construction des bâtiments : chaque niveau divise la durée par (1 + niveau).\')');
        $this->addSql('INSERT INTO building_type (code, name, effect, base_cost_metal, base_cost_crystal, base_cost_deuterium, cost_factor, effect_base, effect_growth, energy_consumption, deuterium_consumption, temperature_base, temperature_coefficient, sort_order, description) VALUES (\'nanite_factory\', \'Usine de nanites\', \'nanite_factory\', 1000000, 500000, 100000, 2, 0, 1, 0, 0, 1, 0, 100, \'Divise par deux la durée de construction des bâtiments à chaque niveau.\')');
    }

    public function down(Schema $schema): void
    {
        $this->addSql("DELETE FROM building_type WHERE code IN ('robot_factory', 'nanite_factory')");
        $this->addSql('ALTER TABLE building_queue_item DROP CONSTRAINT FK_9403026D71F7E88B');
        $this->addSql('ALTER TABLE building_queue_item DROP CONSTRAINT FK_9403026DA25E9820');
        $this->addSql('ALTER TABLE building_queue_item DROP CONSTRAINT FK_9403026DC54C8C93');
        $this->addSql('DROP TABLE building_queue_item');
        $this->addSql('DROP TABLE building_queue_item_audit');
    }
}
