<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261006193439 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Flottes : constitution à partir de l’inventaire d’une planète';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE fleet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(40) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, empire_id INT NOT NULL, planet_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A05E1E476E6A432A ON fleet (empire_id)');
        $this->addSql('CREATE INDEX IDX_A05E1E47A25E9820 ON fleet (planet_id)');
        $this->addSql('CREATE TABLE fleet_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, extra_data JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_92aaa7055d38cd6021384ce621106985_idx ON fleet_audit (type)');
        $this->addSql('CREATE INDEX object_id_92aaa7055d38cd6021384ce621106985_idx ON fleet_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_92aaa7055d38cd6021384ce621106985_idx ON fleet_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_92aaa7055d38cd6021384ce621106985_idx ON fleet_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_92aaa7055d38cd6021384ce621106985_idx ON fleet_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_92aaa7055d38cd6021384ce621106985_idx ON fleet_audit (created_at)');
        $this->addSql('CREATE TABLE fleet_ship (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, fleet_id INT NOT NULL, type_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX fleet_ship_unique ON fleet_ship (fleet_id, type_id)');
        $this->addSql('CREATE INDEX IDX_352580994B061DF9 ON fleet_ship (fleet_id)');
        $this->addSql('CREATE INDEX IDX_35258099C54C8C93 ON fleet_ship (type_id)');
        $this->addSql('CREATE TABLE fleet_ship_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, extra_data JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_11a7cc537921876c63cfc0754d3fbbcd_idx ON fleet_ship_audit (type)');
        $this->addSql('CREATE INDEX object_id_11a7cc537921876c63cfc0754d3fbbcd_idx ON fleet_ship_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_11a7cc537921876c63cfc0754d3fbbcd_idx ON fleet_ship_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_11a7cc537921876c63cfc0754d3fbbcd_idx ON fleet_ship_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_11a7cc537921876c63cfc0754d3fbbcd_idx ON fleet_ship_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_11a7cc537921876c63cfc0754d3fbbcd_idx ON fleet_ship_audit (created_at)');
        $this->addSql('ALTER TABLE fleet ADD CONSTRAINT FK_A05E1E476E6A432A FOREIGN KEY (empire_id) REFERENCES empire (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fleet ADD CONSTRAINT FK_A05E1E47A25E9820 FOREIGN KEY (planet_id) REFERENCES planet (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fleet_ship ADD CONSTRAINT FK_352580994B061DF9 FOREIGN KEY (fleet_id) REFERENCES fleet (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fleet_ship ADD CONSTRAINT FK_35258099C54C8C93 FOREIGN KEY (type_id) REFERENCES ship_type (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE fleet DROP CONSTRAINT FK_A05E1E476E6A432A');
        $this->addSql('ALTER TABLE fleet DROP CONSTRAINT FK_A05E1E47A25E9820');
        $this->addSql('ALTER TABLE fleet_ship DROP CONSTRAINT FK_352580994B061DF9');
        $this->addSql('ALTER TABLE fleet_ship DROP CONSTRAINT FK_35258099C54C8C93');
        $this->addSql('DROP TABLE fleet');
        $this->addSql('DROP TABLE fleet_audit');
        $this->addSql('DROP TABLE fleet_ship');
        $this->addSql('DROP TABLE fleet_ship_audit');
    }
}
