<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261006143703 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Recherche : technologies (contenu réglable), niveaux par empire, prérequis croisés ; laboratoire de recherche';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE prerequisite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, level INT NOT NULL, target_building_id INT DEFAULT NULL, target_technology_id INT DEFAULT NULL, required_building_id INT DEFAULT NULL, required_technology_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4594A238CA103118 ON prerequisite (target_building_id)');
        $this->addSql('CREATE INDEX IDX_4594A2385EB9E7D2 ON prerequisite (target_technology_id)');
        $this->addSql('CREATE INDEX IDX_4594A238D691282 ON prerequisite (required_building_id)');
        $this->addSql('CREATE INDEX IDX_4594A23877703349 ON prerequisite (required_technology_id)');
        $this->addSql('CREATE TABLE prerequisite_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, extra_data JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_5aeb8020177caa6104db01bca87d987c_idx ON prerequisite_audit (type)');
        $this->addSql('CREATE INDEX object_id_5aeb8020177caa6104db01bca87d987c_idx ON prerequisite_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_5aeb8020177caa6104db01bca87d987c_idx ON prerequisite_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_5aeb8020177caa6104db01bca87d987c_idx ON prerequisite_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_5aeb8020177caa6104db01bca87d987c_idx ON prerequisite_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_5aeb8020177caa6104db01bca87d987c_idx ON prerequisite_audit (created_at)');
        $this->addSql('CREATE TABLE research (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, level INT NOT NULL, empire_id INT NOT NULL, technology_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX research_unique ON research (empire_id, technology_id)');
        $this->addSql('CREATE INDEX IDX_57EB50C26E6A432A ON research (empire_id)');
        $this->addSql('CREATE INDEX IDX_57EB50C24235D463 ON research (technology_id)');
        $this->addSql('CREATE TABLE research_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, extra_data JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_19ca31a4ff4c9ac66621df437f4adac5_idx ON research_audit (type)');
        $this->addSql('CREATE INDEX object_id_19ca31a4ff4c9ac66621df437f4adac5_idx ON research_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_19ca31a4ff4c9ac66621df437f4adac5_idx ON research_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_19ca31a4ff4c9ac66621df437f4adac5_idx ON research_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_19ca31a4ff4c9ac66621df437f4adac5_idx ON research_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_19ca31a4ff4c9ac66621df437f4adac5_idx ON research_audit (created_at)');
        $this->addSql('CREATE TABLE technology (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description TEXT DEFAULT NULL, base_cost_metal DOUBLE PRECISION NOT NULL, base_cost_crystal DOUBLE PRECISION NOT NULL, base_cost_deuterium DOUBLE PRECISION NOT NULL, cost_factor DOUBLE PRECISION NOT NULL, sort_order INT NOT NULL, code VARCHAR(40) NOT NULL, name VARCHAR(60) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX technology_code_unique ON technology (code)');
        $this->addSql('CREATE TABLE technology_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, extra_data JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_e508521d6e2ead5a411355ddcbc8cdd1_idx ON technology_audit (type)');
        $this->addSql('CREATE INDEX object_id_e508521d6e2ead5a411355ddcbc8cdd1_idx ON technology_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_e508521d6e2ead5a411355ddcbc8cdd1_idx ON technology_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_e508521d6e2ead5a411355ddcbc8cdd1_idx ON technology_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_e508521d6e2ead5a411355ddcbc8cdd1_idx ON technology_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_e508521d6e2ead5a411355ddcbc8cdd1_idx ON technology_audit (created_at)');
        $this->addSql('ALTER TABLE prerequisite ADD CONSTRAINT FK_4594A238CA103118 FOREIGN KEY (target_building_id) REFERENCES building_type (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prerequisite ADD CONSTRAINT FK_4594A2385EB9E7D2 FOREIGN KEY (target_technology_id) REFERENCES technology (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prerequisite ADD CONSTRAINT FK_4594A238D691282 FOREIGN KEY (required_building_id) REFERENCES building_type (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prerequisite ADD CONSTRAINT FK_4594A23877703349 FOREIGN KEY (required_technology_id) REFERENCES technology (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE research ADD CONSTRAINT FK_57EB50C26E6A432A FOREIGN KEY (empire_id) REFERENCES empire (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE research ADD CONSTRAINT FK_57EB50C24235D463 FOREIGN KEY (technology_id) REFERENCES technology (id) NOT DEFERRABLE');
        // Une seule cible et un seul requis (Doctrine ne déclare pas les contraintes CHECK)
        $this->addSql('ALTER TABLE prerequisite ADD CONSTRAINT prerequisite_one_target CHECK ((target_building_id IS NULL) <> (target_technology_id IS NULL))');
        $this->addSql('ALTER TABLE prerequisite ADD CONSTRAINT prerequisite_one_requirement CHECK ((required_building_id IS NULL) <> (required_technology_id IS NULL))');

        // Contenu de départ, réglable ensuite dans le panneau (§4.4)
        foreach (self::TECHNOLOGIES as $order => [$code, $name, $metal, $crystal, $deuterium, $factor, $description]) {
            $this->addSql(
                'INSERT INTO technology (code, name, base_cost_metal, base_cost_crystal, base_cost_deuterium, cost_factor, sort_order, description) VALUES (?, ?, ?, ?, ?, ?, ?, ?)',
                [$code, $name, $metal, $crystal, $deuterium, $factor, ($order + 1) * 10, $description],
            );
        }
        $this->addSql(
            'INSERT INTO building_type (code, name, effect, base_cost_metal, base_cost_crystal, base_cost_deuterium, cost_factor, effect_base, effect_growth, energy_consumption, deuterium_consumption, temperature_base, temperature_coefficient, sort_order, description) VALUES (?, ?, ?, 200, 400, 200, 2, 0, 1, 0, 0, 1, 0, 110, ?)',
            ['research_lab', 'Laboratoire de recherche', 'research_lab', 'Ouvre l’arbre technologique. La vitesse de recherche dépend de la somme des laboratoires de l’empire.'],
        );
        foreach (self::PREREQUISITES as [$target, $required, $level]) {
            $this->addSql(
                'INSERT INTO prerequisite (target_building_id, target_technology_id, required_building_id, required_technology_id, level) VALUES ((SELECT id FROM building_type WHERE code = ?), (SELECT id FROM technology WHERE code = ?), (SELECT id FROM building_type WHERE code = ?), (SELECT id FROM technology WHERE code = ?), ?)',
                [$target, $target, $required, $required, $level],
            );
        }
    }

    /** Code, nom, coût du niveau 1 (métal, cristal, deutérium), facteur de coût, description */
    private const array TECHNOLOGIES = [
        ['energy', 'Énergie', 0, 800, 400, 2, 'Maîtrise des flux d’énergie, préalable à la plupart des technologies avancées.'],
        ['computer', 'Informatique', 0, 400, 600, 2, 'Capacités de calcul de l’empire : coordination des flottes et des usines.'],
        ['combustion_drive', 'Propulsion à combustion', 400, 0, 600, 2, 'Moteurs des premiers vaisseaux ; chaque niveau accroît leur vitesse.'],
        ['impulse_drive', 'Propulsion à impulsion', 2000, 4000, 600, 2, 'Moteurs à réaction nucléaire des vaisseaux de taille moyenne.'],
        ['hyperspace_drive', 'Propulsion hyperespace', 10000, 20000, 6000, 2, 'Courbure de l’espace pour les vaisseaux les plus lourds.'],
        ['weapons', 'Armement', 800, 200, 0, 2, 'Renforce l’attaque des vaisseaux et des défenses.'],
        ['shielding', 'Bouclier', 200, 600, 0, 2, 'Renforce les boucliers des vaisseaux et des défenses.'],
        ['armour', 'Coque', 1000, 0, 0, 2, 'Renforce la structure des vaisseaux et des défenses.'],
        ['espionage', 'Espionnage', 200, 1000, 200, 2, 'Précision des rapports d’espionnage et protection contre ceux de l’ennemi.'],
        ['astrophysics', 'Astrophysique', 4000, 8000, 4000, 1.75, 'Permet de coloniser de nouvelles planètes.'],
    ];

    /** Cible, requis (codes de bâtiment ou de technologie, distincts entre eux), niveau requis */
    private const array PREREQUISITES = [
        ['fusion_reactor', 'deuterium_synthesizer', 5],
        ['fusion_reactor', 'energy', 3],
        ['nanite_factory', 'robot_factory', 10],
        ['nanite_factory', 'computer', 10],
        ['energy', 'research_lab', 1],
        ['computer', 'research_lab', 1],
        ['combustion_drive', 'research_lab', 1],
        ['combustion_drive', 'energy', 1],
        ['impulse_drive', 'research_lab', 2],
        ['impulse_drive', 'energy', 1],
        ['hyperspace_drive', 'research_lab', 7],
        ['hyperspace_drive', 'energy', 5],
        ['hyperspace_drive', 'shielding', 5],
        ['weapons', 'research_lab', 4],
        ['shielding', 'research_lab', 6],
        ['shielding', 'energy', 3],
        ['armour', 'research_lab', 2],
        ['espionage', 'research_lab', 3],
        ['astrophysics', 'research_lab', 3],
        ['astrophysics', 'espionage', 4],
        ['astrophysics', 'impulse_drive', 3],
    ];

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE prerequisite DROP CONSTRAINT FK_4594A238CA103118');
        $this->addSql('ALTER TABLE prerequisite DROP CONSTRAINT FK_4594A2385EB9E7D2');
        $this->addSql('ALTER TABLE prerequisite DROP CONSTRAINT FK_4594A238D691282');
        $this->addSql('ALTER TABLE prerequisite DROP CONSTRAINT FK_4594A23877703349');
        $this->addSql('ALTER TABLE research DROP CONSTRAINT FK_57EB50C26E6A432A');
        $this->addSql('ALTER TABLE research DROP CONSTRAINT FK_57EB50C24235D463');
        $this->addSql('DROP TABLE prerequisite');
        $this->addSql('DROP TABLE prerequisite_audit');
        $this->addSql('DROP TABLE research');
        $this->addSql('DROP TABLE research_audit');
        $this->addSql('DROP TABLE technology');
        $this->addSql('DROP TABLE technology_audit');
        $this->addSql('DELETE FROM building_type WHERE code = \'research_lab\'');
    }
}
