<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261006082303 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Événements planifiés';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE scheduled_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, attempts INT NOT NULL, error TEXT DEFAULT NULL, type VARCHAR(60) NOT NULL, due_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, payload JSON NOT NULL, planet_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX scheduled_event_due_idx ON scheduled_event (status, due_at)');
        $this->addSql('CREATE INDEX IDX_79D3538CA25E9820 ON scheduled_event (planet_id)');
        $this->addSql('ALTER TABLE scheduled_event ADD CONSTRAINT FK_79D3538CA25E9820 FOREIGN KEY (planet_id) REFERENCES planet (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE scheduled_event DROP CONSTRAINT FK_79D3538CA25E9820');
        $this->addSql('DROP TABLE scheduled_event');
    }
}
