<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261006152748 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Flotte : classes de combat et types de vaisseaux (contenu réglable)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE ship_class (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description TEXT DEFAULT NULL, sort_order INT NOT NULL, code VARCHAR(40) NOT NULL, name VARCHAR(60) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX ship_class_code_unique ON ship_class (code)');
        $this->addSql('CREATE TABLE ship_class_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, extra_data JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_a8ec0dfb98cc6fffa1a745271122bbd4_idx ON ship_class_audit (type)');
        $this->addSql('CREATE INDEX object_id_a8ec0dfb98cc6fffa1a745271122bbd4_idx ON ship_class_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_a8ec0dfb98cc6fffa1a745271122bbd4_idx ON ship_class_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_a8ec0dfb98cc6fffa1a745271122bbd4_idx ON ship_class_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_a8ec0dfb98cc6fffa1a745271122bbd4_idx ON ship_class_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_a8ec0dfb98cc6fffa1a745271122bbd4_idx ON ship_class_audit (created_at)');
        $this->addSql('CREATE TABLE ship_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description TEXT DEFAULT NULL, cost_metal DOUBLE PRECISION NOT NULL, cost_crystal DOUBLE PRECISION NOT NULL, cost_deuterium DOUBLE PRECISION NOT NULL, attack INT NOT NULL, shield INT NOT NULL, structure INT NOT NULL, speed INT NOT NULL, cargo INT NOT NULL, fuel_consumption INT NOT NULL, fuel_capacity INT NOT NULL, sort_order INT NOT NULL, code VARCHAR(40) NOT NULL, name VARCHAR(60) NOT NULL, category VARCHAR(20) NOT NULL, ship_class_id INT DEFAULT NULL, drive_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX ship_type_code_unique ON ship_type (code)');
        $this->addSql('CREATE INDEX IDX_2EFC8468D90D3BC5 ON ship_type (ship_class_id)');
        $this->addSql('CREATE INDEX IDX_2EFC846886E5E0C4 ON ship_type (drive_id)');
        $this->addSql('CREATE TABLE ship_type_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, extra_data JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_552dfe0f3e00e7fca5b4e1662e2cd745_idx ON ship_type_audit (type)');
        $this->addSql('CREATE INDEX object_id_552dfe0f3e00e7fca5b4e1662e2cd745_idx ON ship_type_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_552dfe0f3e00e7fca5b4e1662e2cd745_idx ON ship_type_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_552dfe0f3e00e7fca5b4e1662e2cd745_idx ON ship_type_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_552dfe0f3e00e7fca5b4e1662e2cd745_idx ON ship_type_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_552dfe0f3e00e7fca5b4e1662e2cd745_idx ON ship_type_audit (created_at)');
        $this->addSql('ALTER TABLE ship_type ADD CONSTRAINT FK_2EFC8468D90D3BC5 FOREIGN KEY (ship_class_id) REFERENCES ship_class (id)');
        $this->addSql('ALTER TABLE ship_type ADD CONSTRAINT FK_2EFC846886E5E0C4 FOREIGN KEY (drive_id) REFERENCES technology (id)');

        // Contenu de départ, réglable ensuite dans le panneau (§4.5) ; valeurs provisoires avant l'équilibrage (§7)
        foreach (self::CLASSES as $order => [$code, $name, $description]) {
            $this->addSql('INSERT INTO ship_class (code, name, description, sort_order) VALUES (?, ?, ?, ?)', [$code, $name, $description, ($order + 1) * 10]);
        }
        foreach (self::TYPES as $order => [$code, $name, $category, $class, $drive, $metal, $crystal, $deuterium, $attack, $shield, $structure, $speed, $cargo, $fuel, $tank, $description]) {
            $this->addSql(
                'INSERT INTO ship_type (code, name, category, ship_class_id, drive_id, cost_metal, cost_crystal, cost_deuterium, attack, shield, structure, speed, cargo, fuel_consumption, fuel_capacity, sort_order, description) VALUES (?, ?, ?, (SELECT id FROM ship_class WHERE code = ?), (SELECT id FROM technology WHERE code = ?), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
                [$code, $name, $category, $class, $drive, $metal, $crystal, $deuterium, $attack, $shield, $structure, $speed, $cargo, $fuel, $tank, ($order + 1) * 10, $description],
            );
        }
    }

    /** Code, nom, description */
    private const array CLASSES = [
        ['interceptor', 'Intercepteur', 'Chasseurs rapides, efficaces contre les bombardiers, pénalisés face aux croiseurs.'],
        ['bomber', 'Bombardier', 'Puissance de feu contre les grosses coques, vulnérables aux intercepteurs.'],
        ['cruiser', 'Croiseur', 'Polyvalents et résistants, ils dominent les intercepteurs.'],
        ['support', 'Support', 'Vaisseaux d’appui (transport, ravitaillement) engagés en dernier.'],
        ['capital', 'Capital', 'Unités lourdes de fin de partie.'],
    ];

    /**
     * Code, nom, catégorie, classe, propulsion, coût (métal, cristal, deutérium), attaque, bouclier, structure, vitesse,
     * cargo, consommation, réservoir, description.
     */
    private const array TYPES = [
        ['small_cargo', 'Transporteur léger', 'civil', null, 'combustion_drive', 2000, 2000, 0, 5, 10, 4000, 5000, 5000, 10, 400, 'Transport rapide de petites quantités de ressources.'],
        ['large_cargo', 'Transporteur lourd', 'civil', null, 'combustion_drive', 6000, 6000, 0, 5, 25, 12000, 7500, 25000, 50, 1500, 'Transport de grandes quantités de ressources.'],
        ['colony_ship', 'Colonisateur', 'civil', null, 'impulse_drive', 10000, 20000, 10000, 50, 100, 30000, 2500, 7500, 1000, 15000, 'Fonde une colonie sur une planète libre.'],
        ['recycler', 'Recycleur', 'civil', null, 'combustion_drive', 10000, 6000, 2000, 1, 10, 16000, 2000, 20000, 300, 6000, 'Récupère les champs de débris.'],
        ['espionage_probe', 'Sonde d’espionnage', 'civil', null, 'combustion_drive', 0, 1000, 0, 0, 0, 1000, 100000000, 5, 1, 50, 'Récolte des informations sur une position.'],
        ['light_fighter', 'Chasseur léger', 'military', 'interceptor', 'combustion_drive', 3000, 1000, 0, 50, 10, 4000, 12500, 50, 20, 400, 'Chasseur de base, rapide et peu coûteux.'],
        ['heavy_fighter', 'Chasseur lourd', 'military', 'bomber', 'impulse_drive', 6000, 4000, 0, 150, 25, 10000, 10000, 100, 75, 1500, 'Chasseur blindé, armé contre les coques lourdes.'],
        ['cruiser', 'Croiseur', 'military', 'cruiser', 'impulse_drive', 20000, 7000, 2000, 400, 50, 27000, 15000, 800, 300, 6000, 'Vaisseau de ligne polyvalent.'],
        ['battleship', 'Vaisseau de bataille', 'military', 'cruiser', 'hyperspace_drive', 45000, 15000, 0, 1000, 200, 60000, 10000, 1500, 500, 10000, 'Colonne vertébrale des flottes de combat.'],
        ['destroyer', 'Destroyer', 'military', 'capital', 'hyperspace_drive', 60000, 50000, 15000, 2000, 500, 110000, 5000, 2000, 1000, 20000, 'Vaisseau lourd taillé pour les batailles rangées.'],
        ['guardian', 'Gardien', 'military', 'capital', 'hyperspace_drive', 5000000, 4000000, 1000000, 200000, 50000, 9000000, 100, 1000000, 1, 50000, 'Unité capitale de fin de partie.'],
    ];

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE ship_type DROP CONSTRAINT FK_2EFC8468D90D3BC5');
        $this->addSql('ALTER TABLE ship_type DROP CONSTRAINT FK_2EFC846886E5E0C4');
        $this->addSql('DROP TABLE ship_class');
        $this->addSql('DROP TABLE ship_class_audit');
        $this->addSql('DROP TABLE ship_type');
        $this->addSql('DROP TABLE ship_type_audit');
    }
}
