<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261001135434 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Univers (galaxie, système stellaire, planète) et file de messages Messenger';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE galaxy (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number INT NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX galaxy_number_unique ON galaxy (number)');
        $this->addSql('CREATE TABLE planet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, temperature INT NOT NULL, angle DOUBLE PRECISION NOT NULL, orbit INT NOT NULL, radius DOUBLE PRECISION NOT NULL, system_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX planet_system_orbit_unique ON planet (system_id, orbit)');
        $this->addSql('CREATE INDEX IDX_68136AA5D0952FA5 ON planet (system_id)');
        $this->addSql('CREATE TABLE star_system (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number INT NOT NULL, x DOUBLE PRECISION NOT NULL, y DOUBLE PRECISION NOT NULL, galaxy_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX star_system_galaxy_number_unique ON star_system (galaxy_id, number)');
        $this->addSql('CREATE INDEX IDX_FB9A8A80B61FAB2 ON star_system (galaxy_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE planet ADD CONSTRAINT FK_68136AA5D0952FA5 FOREIGN KEY (system_id) REFERENCES star_system (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE star_system ADD CONSTRAINT FK_FB9A8A80B61FAB2 FOREIGN KEY (galaxy_id) REFERENCES galaxy (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE planet DROP CONSTRAINT FK_68136AA5D0952FA5');
        $this->addSql('ALTER TABLE star_system DROP CONSTRAINT FK_FB9A8A80B61FAB2');
        $this->addSql('DROP TABLE galaxy');
        $this->addSql('DROP TABLE planet');
        $this->addSql('DROP TABLE star_system');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
