<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261009195301 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Exploration : gabarits de quêtes, issues et événements vécus par les flottes';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE exploration_event_instance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, title VARCHAR(80) NOT NULL, text TEXT NOT NULL, outcome_label VARCHAR(80) DEFAULT NULL, report TEXT DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, resolved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, location_label VARCHAR(60) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, speed_percent INT NOT NULL, location_galaxy_id INT NOT NULL, location_system_id INT DEFAULT NULL, location_anchor_x DOUBLE PRECISION NOT NULL, location_anchor_y DOUBLE PRECISION NOT NULL, location_local_x DOUBLE PRECISION DEFAULT NULL, location_local_y DOUBLE PRECISION DEFAULT NULL, location_planet_id INT DEFAULT NULL, outcome_id INT DEFAULT NULL, template_id INT DEFAULT NULL, empire_id INT NOT NULL, fleet_id INT DEFAULT NULL, previous_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX exploration_event_empire_idx ON exploration_event_instance (empire_id, created_at)');
        $this->addSql('CREATE INDEX IDX_C343C8A5E6EE6D63 ON exploration_event_instance (outcome_id)');
        $this->addSql('CREATE INDEX IDX_C343C8A55DA0FB8 ON exploration_event_instance (template_id)');
        $this->addSql('CREATE INDEX IDX_C343C8A56E6A432A ON exploration_event_instance (empire_id)');
        $this->addSql('CREATE INDEX IDX_C343C8A54B061DF9 ON exploration_event_instance (fleet_id)');
        $this->addSql('CREATE INDEX IDX_C343C8A52DE62210 ON exploration_event_instance (previous_id)');
        $this->addSql('CREATE TABLE quest_outcome (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(80) NOT NULL, text TEXT NOT NULL, weight INT NOT NULL, metal INT NOT NULL, crystal INT NOT NULL, deuterium INT NOT NULL, ship_loss_percent INT NOT NULL, template_id INT NOT NULL, next_quest_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_649BD0895DA0FB8 ON quest_outcome (template_id)');
        $this->addSql('CREATE INDEX IDX_649BD0891884D21A ON quest_outcome (next_quest_id)');
        $this->addSql('CREATE TABLE quest_outcome_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, extra_data JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_1c95f54a986ec9e19f302413062caa20_idx ON quest_outcome_audit (type)');
        $this->addSql('CREATE INDEX object_id_1c95f54a986ec9e19f302413062caa20_idx ON quest_outcome_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_1c95f54a986ec9e19f302413062caa20_idx ON quest_outcome_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_1c95f54a986ec9e19f302413062caa20_idx ON quest_outcome_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_1c95f54a986ec9e19f302413062caa20_idx ON quest_outcome_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_1c95f54a986ec9e19f302413062caa20_idx ON quest_outcome_audit (created_at)');
        $this->addSql('CREATE TABLE quest_template (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(60) NOT NULL, name VARCHAR(80) NOT NULL, text TEXT NOT NULL, active BOOLEAN NOT NULL, resolution VARCHAR(20) NOT NULL, chance INT NOT NULL, response_minutes INT NOT NULL, required_technology_level INT NOT NULL, required_ship_count INT NOT NULL, required_cargo_metal INT NOT NULL, required_cargo_crystal INT NOT NULL, required_cargo_deuterium INT NOT NULL, required_technology_id INT DEFAULT NULL, required_ship_type_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_763AA02677153098 ON quest_template (code)');
        $this->addSql('CREATE INDEX IDX_763AA02677703349 ON quest_template (required_technology_id)');
        $this->addSql('CREATE INDEX IDX_763AA0263B2E6CD6 ON quest_template (required_ship_type_id)');
        $this->addSql('CREATE TABLE quest_template_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, extra_data JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_fcd3ba746dbee222ef1fee9cedecee43_idx ON quest_template_audit (type)');
        $this->addSql('CREATE INDEX object_id_fcd3ba746dbee222ef1fee9cedecee43_idx ON quest_template_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_fcd3ba746dbee222ef1fee9cedecee43_idx ON quest_template_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_fcd3ba746dbee222ef1fee9cedecee43_idx ON quest_template_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_fcd3ba746dbee222ef1fee9cedecee43_idx ON quest_template_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_fcd3ba746dbee222ef1fee9cedecee43_idx ON quest_template_audit (created_at)');
        $this->addSql('ALTER TABLE exploration_event_instance ADD CONSTRAINT FK_C343C8A5E6EE6D63 FOREIGN KEY (outcome_id) REFERENCES quest_outcome (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exploration_event_instance ADD CONSTRAINT FK_C343C8A55DA0FB8 FOREIGN KEY (template_id) REFERENCES quest_template (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exploration_event_instance ADD CONSTRAINT FK_C343C8A56E6A432A FOREIGN KEY (empire_id) REFERENCES empire (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exploration_event_instance ADD CONSTRAINT FK_C343C8A54B061DF9 FOREIGN KEY (fleet_id) REFERENCES fleet (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exploration_event_instance ADD CONSTRAINT FK_C343C8A52DE62210 FOREIGN KEY (previous_id) REFERENCES exploration_event_instance (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE quest_outcome ADD CONSTRAINT FK_649BD0895DA0FB8 FOREIGN KEY (template_id) REFERENCES quest_template (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE quest_outcome ADD CONSTRAINT FK_649BD0891884D21A FOREIGN KEY (next_quest_id) REFERENCES quest_template (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE quest_template ADD CONSTRAINT FK_763AA02677703349 FOREIGN KEY (required_technology_id) REFERENCES technology (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE quest_template ADD CONSTRAINT FK_763AA0263B2E6CD6 FOREIGN KEY (required_ship_type_id) REFERENCES ship_type (id) ON DELETE SET NULL NOT DEFERRABLE');
        // Bornes des pourcentages (Doctrine ne déclare pas les contraintes CHECK)
        $this->addSql('ALTER TABLE quest_template ADD CONSTRAINT quest_template_chance_check CHECK (chance BETWEEN 0 AND 100)');
        $this->addSql('ALTER TABLE quest_outcome ADD CONSTRAINT quest_outcome_ship_loss_check CHECK (ship_loss_percent BETWEEN 0 AND 100)');

        // Contenu de départ, réglable ensuite dans le panneau (§4.6.4) ; catalogue à étoffer (§7)
        foreach (self::TEMPLATES as [$code, $name, $text, $resolution, $chance, $minutes, $technology, $technologyLevel, $cargoDeuterium]) {
            $this->addSql(
                'INSERT INTO quest_template (code, name, text, active, resolution, chance, response_minutes, required_technology_id, required_technology_level, required_ship_type_id, required_ship_count, required_cargo_metal, required_cargo_crystal, required_cargo_deuterium) VALUES (?, ?, ?, true, ?, ?, ?, (SELECT id FROM technology WHERE code = ?), ?, NULL, 0, 0, 0, ?)',
                [$code, $name, $text, $resolution, $chance, $minutes, $technology, $technologyLevel, $cargoDeuterium],
            );
        }
        foreach (self::OUTCOMES as [$template, $label, $text, $weight, $metal, $crystal, $deuterium, $loss, $next]) {
            $this->addSql(
                'INSERT INTO quest_outcome (template_id, label, text, weight, metal, crystal, deuterium, ship_loss_percent, next_quest_id) VALUES ((SELECT id FROM quest_template WHERE code = ?), ?, ?, ?, ?, ?, ?, ?, (SELECT id FROM quest_template WHERE code = ?))',
                [$template, $label, $text, $weight, $metal, $crystal, $deuterium, $loss, $next],
            );
        }
    }

    /**
     * Code, titre, texte, résolution, probabilité (%), délai de réponse (min), technologie requise et niveau,
     * deutérium requis en cargaison.
     */
    private const array TEMPLATES = [
        ['derelict_convoy', 'Épave d’un convoi', 'Vos capteurs repèrent les restes d’un convoi marchand à la dérive. Une partie de sa cargaison semble intacte.', 'automatic', 20, 1440, null, 0, 0],
        ['ion_storm', 'Tempête ionique', 'Une tempête ionique balaie le secteur au moment où la flotte y pénètre.', 'automatic', 10, 1440, null, 0, 0],
        ['crystal_nebula', 'Nébuleuse cristalline', 'Grâce à vos relevés astrophysiques, la flotte identifie une nébuleuse chargée de cristaux.', 'automatic', 10, 1440, 'astrophysics', 1, 0],
        ['distress_signal', 'Signal de détresse', 'Un signal de détresse, faible mais régulier, provient d’un champ d’astéroïdes voisin.', 'choice', 8, 720, null, 0, 0],
        ['relief_convoy', 'Convoi de secours', 'Le convoi de secours est immobilisé, réservoirs à sec. Son commandant vous demande du deutérium et promet de vous récompenser.', 'choice', 0, 120, null, 0, 1000],
    ];

    /** Quête, libellé, dénouement, poids, métal, cristal, deutérium, % de vaisseaux perdus, quête suivante */
    private const array OUTCOMES = [
        ['derelict_convoy', 'Soutes intactes', 'Vos équipes récupèrent des conteneurs scellés.', 3, 2000, 1000, 0, 0, null],
        ['derelict_convoy', 'Champ de mines', 'Le convoi servait d’appât : des mines dormantes s’activent au passage de la flotte.', 1, 0, 0, 0, 10, null],
        ['ion_storm', 'Abri trouvé', 'La flotte se met à couvert derrière une lune et attend la fin de la tempête.', 3, 0, 0, 0, 0, null],
        ['ion_storm', 'Soutes perforées', 'Les décharges endommagent les soutes : une partie du deutérium transporté s’échappe.', 1, 0, 0, -500, 0, null],
        ['crystal_nebula', 'Récolte', 'Les soutes se remplissent de cristaux purs.', 1, 0, 3000, 0, 0, null],
        ['distress_signal', 'Enquêter', 'La flotte remonte le signal jusqu’à un vaisseau endommagé : il escortait un convoi de secours, tombé en panne de carburant.', 1, 0, 0, 0, 0, 'relief_convoy'],
        ['distress_signal', 'Ignorer le signal', 'La flotte poursuit sa route ; le signal s’éteint peu après.', 1, 0, 0, 0, 0, null],
        ['relief_convoy', 'Livrer 1 000 de deutérium', 'Le convoi repart ; en remerciement, il vous cède une partie de sa cargaison de métal.', 1, 6000, 0, -1000, 0, null],
        ['relief_convoy', 'Refuser', 'Vous laissez le convoi à son sort.', 1, 0, 0, 0, 0, null],
    ];

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE exploration_event_instance DROP CONSTRAINT FK_C343C8A5E6EE6D63');
        $this->addSql('ALTER TABLE exploration_event_instance DROP CONSTRAINT FK_C343C8A55DA0FB8');
        $this->addSql('ALTER TABLE exploration_event_instance DROP CONSTRAINT FK_C343C8A56E6A432A');
        $this->addSql('ALTER TABLE exploration_event_instance DROP CONSTRAINT FK_C343C8A54B061DF9');
        $this->addSql('ALTER TABLE exploration_event_instance DROP CONSTRAINT FK_C343C8A52DE62210');
        $this->addSql('ALTER TABLE quest_outcome DROP CONSTRAINT FK_649BD0895DA0FB8');
        $this->addSql('ALTER TABLE quest_outcome DROP CONSTRAINT FK_649BD0891884D21A');
        $this->addSql('ALTER TABLE quest_template DROP CONSTRAINT FK_763AA02677703349');
        $this->addSql('ALTER TABLE quest_template DROP CONSTRAINT FK_763AA0263B2E6CD6');
        $this->addSql('DROP TABLE exploration_event_instance');
        $this->addSql('DROP TABLE quest_outcome');
        $this->addSql('DROP TABLE quest_outcome_audit');
        $this->addSql('DROP TABLE quest_template');
        $this->addSql('DROP TABLE quest_template_audit');
    }
}
