<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261006144756 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'File de recherche : une recherche en cours par empire';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE research_queue_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, paid_metal DOUBLE PRECISION NOT NULL, paid_crystal DOUBLE PRECISION NOT NULL, paid_deuterium DOUBLE PRECISION NOT NULL, target_level INT NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, event_id INT DEFAULT NULL, empire_id INT NOT NULL, planet_id INT NOT NULL, technology_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7E516B8071F7E88B ON research_queue_item (event_id)');
        $this->addSql('CREATE UNIQUE INDEX research_queue_item_empire_unique ON research_queue_item (empire_id)');
        $this->addSql('CREATE INDEX IDX_7E516B80A25E9820 ON research_queue_item (planet_id)');
        $this->addSql('CREATE INDEX IDX_7E516B804235D463 ON research_queue_item (technology_id)');
        $this->addSql('CREATE TABLE research_queue_item_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, extra_data JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_b3e4aa48b3d0861830c518308860e329_idx ON research_queue_item_audit (type)');
        $this->addSql('CREATE INDEX object_id_b3e4aa48b3d0861830c518308860e329_idx ON research_queue_item_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_b3e4aa48b3d0861830c518308860e329_idx ON research_queue_item_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_b3e4aa48b3d0861830c518308860e329_idx ON research_queue_item_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_b3e4aa48b3d0861830c518308860e329_idx ON research_queue_item_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_b3e4aa48b3d0861830c518308860e329_idx ON research_queue_item_audit (created_at)');
        $this->addSql('ALTER TABLE research_queue_item ADD CONSTRAINT FK_7E516B8071F7E88B FOREIGN KEY (event_id) REFERENCES scheduled_event (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE research_queue_item ADD CONSTRAINT FK_7E516B806E6A432A FOREIGN KEY (empire_id) REFERENCES empire (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE research_queue_item ADD CONSTRAINT FK_7E516B80A25E9820 FOREIGN KEY (planet_id) REFERENCES planet (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE research_queue_item ADD CONSTRAINT FK_7E516B804235D463 FOREIGN KEY (technology_id) REFERENCES technology (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE research_queue_item DROP CONSTRAINT FK_7E516B8071F7E88B');
        $this->addSql('ALTER TABLE research_queue_item DROP CONSTRAINT FK_7E516B806E6A432A');
        $this->addSql('ALTER TABLE research_queue_item DROP CONSTRAINT FK_7E516B80A25E9820');
        $this->addSql('ALTER TABLE research_queue_item DROP CONSTRAINT FK_7E516B804235D463');
        $this->addSql('DROP TABLE research_queue_item');
        $this->addSql('DROP TABLE research_queue_item_audit');
    }
}
