<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261009213208 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Combat : matrice des classes (multiplicateur de dégâts par paire de classes)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE class_matchup (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, multiplier DOUBLE PRECISION NOT NULL, attacker_id INT NOT NULL, defender_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX class_matchup_pair_unique ON class_matchup (attacker_id, defender_id)');
        $this->addSql('CREATE INDEX IDX_109831AD65F8CAE3 ON class_matchup (attacker_id)');
        $this->addSql('CREATE INDEX IDX_109831AD4A3E3B6F ON class_matchup (defender_id)');
        $this->addSql('CREATE TABLE class_matchup_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, extra_data JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_9405f1c91dba7fe731e4e6c8d782a04e_idx ON class_matchup_audit (type)');
        $this->addSql('CREATE INDEX object_id_9405f1c91dba7fe731e4e6c8d782a04e_idx ON class_matchup_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_9405f1c91dba7fe731e4e6c8d782a04e_idx ON class_matchup_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_9405f1c91dba7fe731e4e6c8d782a04e_idx ON class_matchup_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_9405f1c91dba7fe731e4e6c8d782a04e_idx ON class_matchup_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_9405f1c91dba7fe731e4e6c8d782a04e_idx ON class_matchup_audit (created_at)');
        $this->addSql('ALTER TABLE class_matchup ADD CONSTRAINT FK_109831AD65F8CAE3 FOREIGN KEY (attacker_id) REFERENCES ship_class (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE class_matchup ADD CONSTRAINT FK_109831AD4A3E3B6F FOREIGN KEY (defender_id) REFERENCES ship_class (id) ON DELETE CASCADE NOT DEFERRABLE');
        // Bornes de ClassMatchup::MIN / MAX (Doctrine ne déclare pas les contraintes CHECK)
        $this->addSql('ALTER TABLE class_matchup ADD CONSTRAINT class_matchup_multiplier_check CHECK (multiplier BETWEEN 0.1 AND 10)');

        // Contenu de départ (§4.7, « pierre-feuille-ciseaux »), réglable ensuite dans le panneau ; valeurs provisoires
        // avant l'équilibrage (§7). Paires absentes : neutres.
        foreach (self::MATCHUPS as [$attacker, $defender, $multiplier]) {
            $this->addSql(
                'INSERT INTO class_matchup (attacker_id, defender_id, multiplier) SELECT a.id, d.id, ? FROM ship_class a, ship_class d WHERE a.code = ? AND d.code = ?',
                [$multiplier, $attacker, $defender],
            );
        }
    }

    /** Classe attaquante, classe visée, multiplicateur */
    private const array MATCHUPS = [
        // Intercepteurs : efficaces contre les bombardiers, pénalisés face aux croiseurs
        ['interceptor', 'bomber', 1.5],
        ['interceptor', 'cruiser', 0.75],
        ['interceptor', 'capital', 0.5],
        // Bombardiers : puissance de feu contre les grosses coques, maladroits contre les intercepteurs
        ['bomber', 'cruiser', 1.5],
        ['bomber', 'capital', 2.0],
        ['bomber', 'interceptor', 0.75],
        // Croiseurs : dominent les intercepteurs
        ['cruiser', 'interceptor', 1.5],
        ['cruiser', 'bomber', 1.25],
        // Capitaux : écrasent les croiseurs, peinent à toucher les petits vaisseaux
        ['capital', 'cruiser', 1.5],
        ['capital', 'interceptor', 0.75],
    ];

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE class_matchup DROP CONSTRAINT FK_109831AD65F8CAE3');
        $this->addSql('ALTER TABLE class_matchup DROP CONSTRAINT FK_109831AD4A3E3B6F');
        $this->addSql('DROP TABLE class_matchup');
        $this->addSql('DROP TABLE class_matchup_audit');
    }
}
