<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261006153704 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Chantier spatial : bâtiment, commandes, inventaire des vaisseaux par planète, prérequis des vaisseaux';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE planet_ship (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, planet_id INT NOT NULL, type_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX planet_ship_unique ON planet_ship (planet_id, type_id)');
        $this->addSql('CREATE INDEX IDX_F80D6038A25E9820 ON planet_ship (planet_id)');
        $this->addSql('CREATE INDEX IDX_F80D6038C54C8C93 ON planet_ship (type_id)');
        $this->addSql('CREATE TABLE planet_ship_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, extra_data JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_97cf9a99cab664dfbfcdcb33766ddc20_idx ON planet_ship_audit (type)');
        $this->addSql('CREATE INDEX object_id_97cf9a99cab664dfbfcdcb33766ddc20_idx ON planet_ship_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_97cf9a99cab664dfbfcdcb33766ddc20_idx ON planet_ship_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_97cf9a99cab664dfbfcdcb33766ddc20_idx ON planet_ship_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_97cf9a99cab664dfbfcdcb33766ddc20_idx ON planet_ship_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_97cf9a99cab664dfbfcdcb33766ddc20_idx ON planet_ship_audit (created_at)');
        $this->addSql('CREATE TABLE shipyard_order (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, paid_metal DOUBLE PRECISION NOT NULL, paid_crystal DOUBLE PRECISION NOT NULL, paid_deuterium DOUBLE PRECISION NOT NULL, quantity INT NOT NULL, slot INT NOT NULL, ordered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, event_id INT DEFAULT NULL, planet_id INT NOT NULL, type_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4687F90971F7E88B ON shipyard_order (event_id)');
        $this->addSql('CREATE INDEX shipyard_order_planet_idx ON shipyard_order (planet_id, ends_at)');
        $this->addSql('CREATE INDEX IDX_4687F909A25E9820 ON shipyard_order (planet_id)');
        $this->addSql('CREATE INDEX IDX_4687F909C54C8C93 ON shipyard_order (type_id)');
        $this->addSql('CREATE TABLE shipyard_order_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, extra_data JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_69dbac1c1798849fcc7ce99b29c40752_idx ON shipyard_order_audit (type)');
        $this->addSql('CREATE INDEX object_id_69dbac1c1798849fcc7ce99b29c40752_idx ON shipyard_order_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_69dbac1c1798849fcc7ce99b29c40752_idx ON shipyard_order_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_69dbac1c1798849fcc7ce99b29c40752_idx ON shipyard_order_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_69dbac1c1798849fcc7ce99b29c40752_idx ON shipyard_order_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_69dbac1c1798849fcc7ce99b29c40752_idx ON shipyard_order_audit (created_at)');
        $this->addSql('ALTER TABLE planet_ship ADD CONSTRAINT FK_F80D6038A25E9820 FOREIGN KEY (planet_id) REFERENCES planet (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planet_ship ADD CONSTRAINT FK_F80D6038C54C8C93 FOREIGN KEY (type_id) REFERENCES ship_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shipyard_order ADD CONSTRAINT FK_4687F90971F7E88B FOREIGN KEY (event_id) REFERENCES scheduled_event (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shipyard_order ADD CONSTRAINT FK_4687F909A25E9820 FOREIGN KEY (planet_id) REFERENCES planet (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shipyard_order ADD CONSTRAINT FK_4687F909C54C8C93 FOREIGN KEY (type_id) REFERENCES ship_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prerequisite ADD target_ship_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE prerequisite ADD CONSTRAINT FK_4594A23893E8816 FOREIGN KEY (target_ship_id) REFERENCES ship_type (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_4594A23893E8816 ON prerequisite (target_ship_id)');
        // Une seule cible : bâtiment, technologie ou vaisseau
        $this->addSql('ALTER TABLE prerequisite DROP CONSTRAINT prerequisite_one_target');
        $this->addSql('ALTER TABLE prerequisite ADD CONSTRAINT prerequisite_one_target CHECK (num_nonnulls(target_building_id, target_technology_id, target_ship_id) = 1)');

        // Contenu de départ, réglable ensuite dans le panneau (§4.5)
        $this->addSql(
            'INSERT INTO building_type (code, name, effect, base_cost_metal, base_cost_crystal, base_cost_deuterium, cost_factor, effect_base, effect_growth, energy_consumption, deuterium_consumption, temperature_base, temperature_coefficient, sort_order, description) VALUES (?, ?, ?, 400, 200, 100, 2, 0, 1, 0, 0, 1, 0, 120, ?)',
            ['shipyard', 'Chantier spatial', 'shipyard', 'Construit les vaisseaux. Chaque niveau les construit plus vite, et un poste de construction s’ajoute tous les 4 niveaux.'],
        );
        foreach (self::PREREQUISITES as [$target, $required, $level]) {
            $this->addSql(
                'INSERT INTO prerequisite (target_building_id, target_ship_id, required_building_id, required_technology_id, level) VALUES ((SELECT id FROM building_type WHERE code = ?), (SELECT id FROM ship_type WHERE code = ?), (SELECT id FROM building_type WHERE code = ?), (SELECT id FROM technology WHERE code = ?), ?)',
                [$target, $target, $required, $required, $level],
            );
        }
    }

    /** Cible (bâtiment ou vaisseau), requis (bâtiment ou technologie), niveau requis */
    private const array PREREQUISITES = [
        ['shipyard', 'robot_factory', 2],
        ['small_cargo', 'shipyard', 2],
        ['small_cargo', 'combustion_drive', 2],
        ['large_cargo', 'shipyard', 4],
        ['large_cargo', 'combustion_drive', 6],
        ['colony_ship', 'shipyard', 4],
        ['colony_ship', 'impulse_drive', 3],
        ['recycler', 'shipyard', 4],
        ['recycler', 'combustion_drive', 6],
        ['recycler', 'shielding', 2],
        ['espionage_probe', 'shipyard', 3],
        ['espionage_probe', 'combustion_drive', 3],
        ['espionage_probe', 'espionage', 2],
        ['light_fighter', 'shipyard', 1],
        ['light_fighter', 'combustion_drive', 1],
        ['heavy_fighter', 'shipyard', 3],
        ['heavy_fighter', 'armour', 2],
        ['heavy_fighter', 'impulse_drive', 2],
        ['cruiser', 'shipyard', 5],
        ['cruiser', 'impulse_drive', 4],
        ['cruiser', 'weapons', 3],
        ['battleship', 'shipyard', 7],
        ['battleship', 'hyperspace_drive', 4],
        ['destroyer', 'shipyard', 9],
        ['destroyer', 'hyperspace_drive', 6],
        ['destroyer', 'shielding', 5],
        ['guardian', 'shipyard', 12],
        ['guardian', 'hyperspace_drive', 7],
        ['guardian', 'computer', 10],
    ];

    public function down(Schema $schema): void
    {
        $this->addSql('DELETE FROM prerequisite WHERE target_ship_id IS NOT NULL OR target_building_id = (SELECT id FROM building_type WHERE code = \'shipyard\') OR required_building_id = (SELECT id FROM building_type WHERE code = \'shipyard\')');
        $this->addSql('DELETE FROM building_type WHERE code = \'shipyard\'');
        $this->addSql('ALTER TABLE prerequisite DROP CONSTRAINT prerequisite_one_target');
        $this->addSql('ALTER TABLE prerequisite ADD CONSTRAINT prerequisite_one_target CHECK ((target_building_id IS NULL) <> (target_technology_id IS NULL))');
        $this->addSql('ALTER TABLE planet_ship DROP CONSTRAINT FK_F80D6038A25E9820');
        $this->addSql('ALTER TABLE planet_ship DROP CONSTRAINT FK_F80D6038C54C8C93');
        $this->addSql('ALTER TABLE shipyard_order DROP CONSTRAINT FK_4687F90971F7E88B');
        $this->addSql('ALTER TABLE shipyard_order DROP CONSTRAINT FK_4687F909A25E9820');
        $this->addSql('ALTER TABLE shipyard_order DROP CONSTRAINT FK_4687F909C54C8C93');
        $this->addSql('DROP TABLE planet_ship');
        $this->addSql('DROP TABLE planet_ship_audit');
        $this->addSql('DROP TABLE shipyard_order');
        $this->addSql('DROP TABLE shipyard_order_audit');
        $this->addSql('ALTER TABLE prerequisite DROP CONSTRAINT FK_4594A23893E8816');
        $this->addSql('DROP INDEX IDX_4594A23893E8816');
        $this->addSql('ALTER TABLE prerequisite DROP target_ship_id');
    }
}
