<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261002201430 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Historique des modifications : tables d\'audit des comptes, galaxies et gabarits de forme';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE admin_user_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, extra_data JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_7941a50b47de646aaac54f117b6c474c_idx ON admin_user_audit (type)');
        $this->addSql('CREATE INDEX object_id_7941a50b47de646aaac54f117b6c474c_idx ON admin_user_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_7941a50b47de646aaac54f117b6c474c_idx ON admin_user_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_7941a50b47de646aaac54f117b6c474c_idx ON admin_user_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_7941a50b47de646aaac54f117b6c474c_idx ON admin_user_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_7941a50b47de646aaac54f117b6c474c_idx ON admin_user_audit (created_at)');
        $this->addSql('CREATE TABLE galaxy_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, extra_data JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_15809df8956102fd82e02b1598a16d0a_idx ON galaxy_audit (type)');
        $this->addSql('CREATE INDEX object_id_15809df8956102fd82e02b1598a16d0a_idx ON galaxy_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_15809df8956102fd82e02b1598a16d0a_idx ON galaxy_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_15809df8956102fd82e02b1598a16d0a_idx ON galaxy_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_15809df8956102fd82e02b1598a16d0a_idx ON galaxy_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_15809df8956102fd82e02b1598a16d0a_idx ON galaxy_audit (created_at)');
        $this->addSql('CREATE TABLE galaxy_shape_template_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, extra_data JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_578a34682bceefcd883d4cb0bd8de96f_idx ON galaxy_shape_template_audit (type)');
        $this->addSql('CREATE INDEX object_id_578a34682bceefcd883d4cb0bd8de96f_idx ON galaxy_shape_template_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_578a34682bceefcd883d4cb0bd8de96f_idx ON galaxy_shape_template_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_578a34682bceefcd883d4cb0bd8de96f_idx ON galaxy_shape_template_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_578a34682bceefcd883d4cb0bd8de96f_idx ON galaxy_shape_template_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_578a34682bceefcd883d4cb0bd8de96f_idx ON galaxy_shape_template_audit (created_at)');
        $this->addSql('CREATE TABLE user_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, extra_data JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_e06395edc291d0719bee26fd39a32e8a_idx ON user_audit (type)');
        $this->addSql('CREATE INDEX object_id_e06395edc291d0719bee26fd39a32e8a_idx ON user_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_e06395edc291d0719bee26fd39a32e8a_idx ON user_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_e06395edc291d0719bee26fd39a32e8a_idx ON user_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_e06395edc291d0719bee26fd39a32e8a_idx ON user_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_e06395edc291d0719bee26fd39a32e8a_idx ON user_audit (created_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE admin_user_audit');
        $this->addSql('DROP TABLE galaxy_audit');
        $this->addSql('DROP TABLE galaxy_shape_template_audit');
        $this->addSql('DROP TABLE user_audit');
    }
}
