<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261005205336 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Empires et propriété des planètes';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE empire (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, score INT NOT NULL, name VARCHAR(20) NOT NULL, orientation VARCHAR(20) NOT NULL, founded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, active_planet_id INT NOT NULL, user_id INT NOT NULL, home_planet_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_84B15226A76ED395 ON empire (user_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_84B15226DC8AE164 ON empire (home_planet_id)');
        $this->addSql('CREATE UNIQUE INDEX empire_name_unique ON empire (name)');
        $this->addSql('CREATE INDEX IDX_84B15226B4C8DB14 ON empire (active_planet_id)');
        $this->addSql('CREATE TABLE empire_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, extra_data JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_77372da8c1da9312488001b9eb4ffa0b_idx ON empire_audit (type)');
        $this->addSql('CREATE INDEX object_id_77372da8c1da9312488001b9eb4ffa0b_idx ON empire_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_77372da8c1da9312488001b9eb4ffa0b_idx ON empire_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_77372da8c1da9312488001b9eb4ffa0b_idx ON empire_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_77372da8c1da9312488001b9eb4ffa0b_idx ON empire_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_77372da8c1da9312488001b9eb4ffa0b_idx ON empire_audit (created_at)');
        $this->addSql('ALTER TABLE empire ADD CONSTRAINT FK_84B15226B4C8DB14 FOREIGN KEY (active_planet_id) REFERENCES planet (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE empire ADD CONSTRAINT FK_84B15226A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE empire ADD CONSTRAINT FK_84B15226DC8AE164 FOREIGN KEY (home_planet_id) REFERENCES planet (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planet ADD owner_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE planet ADD CONSTRAINT FK_68136AA57E3C61F9 FOREIGN KEY (owner_id) REFERENCES empire (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_68136AA57E3C61F9 ON planet (owner_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE empire DROP CONSTRAINT FK_84B15226B4C8DB14');
        $this->addSql('ALTER TABLE empire DROP CONSTRAINT FK_84B15226A76ED395');
        $this->addSql('ALTER TABLE empire DROP CONSTRAINT FK_84B15226DC8AE164');
        $this->addSql('DROP TABLE empire');
        $this->addSql('DROP TABLE empire_audit');
        $this->addSql('ALTER TABLE planet DROP CONSTRAINT FK_68136AA57E3C61F9');
        $this->addSql('DROP INDEX IDX_68136AA57E3C61F9');
        $this->addSql('ALTER TABLE planet DROP owner_id');
    }
}
