<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261006200904 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Flottes : état, position, cargaison, carnet d’ordres et déplacement en cours';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE fleet_movement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, speed_percent INT NOT NULL, departed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, arrives_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, origin_galaxy_id INT NOT NULL, origin_system_id INT DEFAULT NULL, origin_anchor_x DOUBLE PRECISION NOT NULL, origin_anchor_y DOUBLE PRECISION NOT NULL, origin_local_x DOUBLE PRECISION DEFAULT NULL, origin_local_y DOUBLE PRECISION DEFAULT NULL, origin_planet_id INT DEFAULT NULL, event_id INT DEFAULT NULL, fleet_id INT NOT NULL, order_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_63291E4471F7E88B ON fleet_movement (event_id)');
        $this->addSql('CREATE UNIQUE INDEX fleet_movement_fleet_unique ON fleet_movement (fleet_id)');
        $this->addSql('CREATE INDEX IDX_63291E448D9F6D38 ON fleet_movement (order_id)');
        $this->addSql('CREATE TABLE fleet_movement_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, extra_data JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_42b6159f63cddcb9946890e8d8a6672f_idx ON fleet_movement_audit (type)');
        $this->addSql('CREATE INDEX object_id_42b6159f63cddcb9946890e8d8a6672f_idx ON fleet_movement_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_42b6159f63cddcb9946890e8d8a6672f_idx ON fleet_movement_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_42b6159f63cddcb9946890e8d8a6672f_idx ON fleet_movement_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_42b6159f63cddcb9946890e8d8a6672f_idx ON fleet_movement_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_42b6159f63cddcb9946890e8d8a6672f_idx ON fleet_movement_audit (created_at)');
        $this->addSql('CREATE TABLE fleet_order (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, failure VARCHAR(255) DEFAULT NULL, order_rank INT NOT NULL, action VARCHAR(20) NOT NULL, destination_label VARCHAR(60) NOT NULL, destination_galaxy_id INT NOT NULL, destination_system_id INT DEFAULT NULL, destination_anchor_x DOUBLE PRECISION NOT NULL, destination_anchor_y DOUBLE PRECISION NOT NULL, destination_local_x DOUBLE PRECISION DEFAULT NULL, destination_local_y DOUBLE PRECISION DEFAULT NULL, destination_planet_id INT DEFAULT NULL, fleet_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX fleet_order_rank_unique ON fleet_order (fleet_id, order_rank)');
        $this->addSql('CREATE INDEX IDX_403649C24B061DF9 ON fleet_order (fleet_id)');
        $this->addSql('CREATE TABLE fleet_order_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, extra_data JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_36643e4d4ebcb2a602af8fb9d192e44c_idx ON fleet_order_audit (type)');
        $this->addSql('CREATE INDEX object_id_36643e4d4ebcb2a602af8fb9d192e44c_idx ON fleet_order_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_36643e4d4ebcb2a602af8fb9d192e44c_idx ON fleet_order_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_36643e4d4ebcb2a602af8fb9d192e44c_idx ON fleet_order_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_36643e4d4ebcb2a602af8fb9d192e44c_idx ON fleet_order_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_36643e4d4ebcb2a602af8fb9d192e44c_idx ON fleet_order_audit (created_at)');
        $this->addSql('ALTER TABLE fleet_movement ADD CONSTRAINT FK_63291E4471F7E88B FOREIGN KEY (event_id) REFERENCES scheduled_event (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fleet_movement ADD CONSTRAINT FK_63291E444B061DF9 FOREIGN KEY (fleet_id) REFERENCES fleet (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fleet_movement ADD CONSTRAINT FK_63291E448D9F6D38 FOREIGN KEY (order_id) REFERENCES fleet_order (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fleet_order ADD CONSTRAINT FK_403649C24B061DF9 FOREIGN KEY (fleet_id) REFERENCES fleet (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fleet DROP CONSTRAINT fk_a05e1e47a25e9820');
        $this->addSql('ALTER TABLE fleet ADD status VARCHAR(20) DEFAULT \'stationed\' NOT NULL');
        $this->addSql('ALTER TABLE fleet ADD cargo_metal DOUBLE PRECISION DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE fleet ADD cargo_crystal DOUBLE PRECISION DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE fleet ADD cargo_deuterium DOUBLE PRECISION DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE fleet ADD location_galaxy_id INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE fleet ADD location_system_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE fleet ADD location_anchor_x DOUBLE PRECISION DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE fleet ADD location_anchor_y DOUBLE PRECISION DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE fleet ADD location_local_x DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE fleet ADD location_local_y DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE fleet ADD location_planet_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE fleet ALTER planet_id DROP NOT NULL');
        // Flottes existantes : stationnées sur leur planète de constitution
        $this->addSql('UPDATE fleet f SET location_galaxy_id = s.galaxy_id, location_system_id = s.id, location_anchor_x = s.x, location_anchor_y = s.y, location_local_x = p.radius * cos(p.angle), location_local_y = p.radius * sin(p.angle), location_planet_id = p.id FROM planet p JOIN star_system s ON s.id = p.system_id WHERE p.id = f.planet_id');
        foreach (['status', 'cargo_metal', 'cargo_crystal', 'cargo_deuterium', 'location_galaxy_id', 'location_anchor_x', 'location_anchor_y'] as $column) {
            $this->addSql(\sprintf('ALTER TABLE fleet ALTER %s DROP DEFAULT', $column));
        }
        $this->addSql('ALTER TABLE fleet ADD CONSTRAINT FK_A05E1E47A25E9820 FOREIGN KEY (planet_id) REFERENCES planet (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE fleet_movement DROP CONSTRAINT FK_63291E4471F7E88B');
        $this->addSql('ALTER TABLE fleet_movement DROP CONSTRAINT FK_63291E444B061DF9');
        $this->addSql('ALTER TABLE fleet_movement DROP CONSTRAINT FK_63291E448D9F6D38');
        $this->addSql('ALTER TABLE fleet_order DROP CONSTRAINT FK_403649C24B061DF9');
        $this->addSql('DROP TABLE fleet_movement');
        $this->addSql('DROP TABLE fleet_movement_audit');
        $this->addSql('DROP TABLE fleet_order');
        $this->addSql('DROP TABLE fleet_order_audit');
        $this->addSql('ALTER TABLE fleet DROP CONSTRAINT FK_A05E1E47A25E9820');
        $this->addSql('ALTER TABLE fleet DROP status');
        $this->addSql('ALTER TABLE fleet DROP cargo_metal');
        $this->addSql('ALTER TABLE fleet DROP cargo_crystal');
        $this->addSql('ALTER TABLE fleet DROP cargo_deuterium');
        $this->addSql('ALTER TABLE fleet DROP location_galaxy_id');
        $this->addSql('ALTER TABLE fleet DROP location_system_id');
        $this->addSql('ALTER TABLE fleet DROP location_anchor_x');
        $this->addSql('ALTER TABLE fleet DROP location_anchor_y');
        $this->addSql('ALTER TABLE fleet DROP location_local_x');
        $this->addSql('ALTER TABLE fleet DROP location_local_y');
        $this->addSql('ALTER TABLE fleet DROP location_planet_id');
        $this->addSql('ALTER TABLE fleet ALTER planet_id SET NOT NULL');
        $this->addSql('ALTER TABLE fleet ADD CONSTRAINT fk_a05e1e47a25e9820 FOREIGN KEY (planet_id) REFERENCES planet (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
