<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261002191851 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Gabarits de forme de galaxie';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE galaxy_shape_template (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, arms INT NOT NULL, arm_tightness DOUBLE PRECISION NOT NULL, arm_width DOUBLE PRECISION NOT NULL, core_radius DOUBLE PRECISION NOT NULL, disk_scale DOUBLE PRECISION NOT NULL, inter_arm_density DOUBLE PRECISION NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX galaxy_shape_template_name_unique ON galaxy_shape_template (name)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE galaxy_shape_template');
    }
}
