<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261002200157 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Journal d\'audit de l\'administration, non modifiable (trigger)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE admin_audit_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actor_id INT DEFAULT NULL, actor_email VARCHAR(180) NOT NULL, action VARCHAR(20) NOT NULL, subject_type VARCHAR(100) NOT NULL, subject_id VARCHAR(64) DEFAULT NULL, subject_label VARCHAR(255) NOT NULL, changes JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX admin_audit_log_occurred_at_idx ON admin_audit_log (occurred_at)');
        $this->addSql('CREATE INDEX admin_audit_log_subject_idx ON admin_audit_log (subject_type, subject_id)');
        // Une entrée du journal ne se modifie jamais, même hors de l'application
        $this->addSql(<<<'SQL'
            CREATE FUNCTION admin_audit_log_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
                RAISE EXCEPTION 'Le journal d''audit n''est pas modifiable.';
            END;
            $$
            SQL);
        $this->addSql('CREATE TRIGGER admin_audit_log_no_update BEFORE UPDATE ON admin_audit_log FOR EACH ROW EXECUTE FUNCTION admin_audit_log_immutable()');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE admin_audit_log');
        $this->addSql('DROP FUNCTION admin_audit_log_immutable()');
    }
}
