<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261005201840 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Demandes de génération de galaxie depuis le panneau d\'administration';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE galaxy_generation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) DEFAULT NULL, system_count INT NOT NULL, seed INT DEFAULT NULL, shape JSON DEFAULT NULL, status VARCHAR(20) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, planet_count INT DEFAULT NULL, error TEXT DEFAULT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, shape_template_id INT DEFAULT NULL, galaxy_id INT DEFAULT NULL, requested_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX galaxy_generation_requested_at_idx ON galaxy_generation (requested_at)');
        $this->addSql('CREATE INDEX IDX_99567D95965749A8 ON galaxy_generation (shape_template_id)');
        $this->addSql('CREATE INDEX IDX_99567D95B61FAB2 ON galaxy_generation (galaxy_id)');
        $this->addSql('CREATE INDEX IDX_99567D954DA1E751 ON galaxy_generation (requested_by_id)');
        $this->addSql('ALTER TABLE galaxy_generation ADD CONSTRAINT FK_99567D95965749A8 FOREIGN KEY (shape_template_id) REFERENCES galaxy_shape_template (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE galaxy_generation ADD CONSTRAINT FK_99567D95B61FAB2 FOREIGN KEY (galaxy_id) REFERENCES galaxy (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE galaxy_generation ADD CONSTRAINT FK_99567D954DA1E751 FOREIGN KEY (requested_by_id) REFERENCES admin_user (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE galaxy_generation DROP CONSTRAINT FK_99567D95965749A8');
        $this->addSql('ALTER TABLE galaxy_generation DROP CONSTRAINT FK_99567D95B61FAB2');
        $this->addSql('ALTER TABLE galaxy_generation DROP CONSTRAINT FK_99567D954DA1E751');
        $this->addSql('DROP TABLE galaxy_generation');
    }
}
