<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261006203543 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Formations des flottes : grille avant / milieu / arrière × gauche / centre / droite';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE formation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fleet_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX formation_fleet_unique ON formation (fleet_id)');
        $this->addSql('CREATE TABLE formation_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, extra_data JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_cd8a984d7ae39620052f3f6f2679a8df_idx ON formation_audit (type)');
        $this->addSql('CREATE INDEX object_id_cd8a984d7ae39620052f3f6f2679a8df_idx ON formation_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_cd8a984d7ae39620052f3f6f2679a8df_idx ON formation_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_cd8a984d7ae39620052f3f6f2679a8df_idx ON formation_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_cd8a984d7ae39620052f3f6f2679a8df_idx ON formation_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_cd8a984d7ae39620052f3f6f2679a8df_idx ON formation_audit (created_at)');
        $this->addSql('CREATE TABLE formation_slot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, grid_row VARCHAR(10) NOT NULL, grid_column VARCHAR(10) NOT NULL, quantity INT NOT NULL, formation_id INT NOT NULL, type_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX formation_slot_unique ON formation_slot (formation_id, grid_row, grid_column, type_id)');
        $this->addSql('CREATE INDEX IDX_FBD1C5275200282E ON formation_slot (formation_id)');
        $this->addSql('CREATE INDEX IDX_FBD1C527C54C8C93 ON formation_slot (type_id)');
        $this->addSql('CREATE TABLE formation_slot_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, extra_data JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_e0f5ad031823ed2db5d62a5883da817a_idx ON formation_slot_audit (type)');
        $this->addSql('CREATE INDEX object_id_e0f5ad031823ed2db5d62a5883da817a_idx ON formation_slot_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_e0f5ad031823ed2db5d62a5883da817a_idx ON formation_slot_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_e0f5ad031823ed2db5d62a5883da817a_idx ON formation_slot_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_e0f5ad031823ed2db5d62a5883da817a_idx ON formation_slot_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_e0f5ad031823ed2db5d62a5883da817a_idx ON formation_slot_audit (created_at)');
        $this->addSql('ALTER TABLE formation ADD CONSTRAINT FK_404021BF4B061DF9 FOREIGN KEY (fleet_id) REFERENCES fleet (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE formation_slot ADD CONSTRAINT FK_FBD1C5275200282E FOREIGN KEY (formation_id) REFERENCES formation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE formation_slot ADD CONSTRAINT FK_FBD1C527C54C8C93 FOREIGN KEY (type_id) REFERENCES ship_type (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE formation DROP CONSTRAINT FK_404021BF4B061DF9');
        $this->addSql('ALTER TABLE formation_slot DROP CONSTRAINT FK_FBD1C5275200282E');
        $this->addSql('ALTER TABLE formation_slot DROP CONSTRAINT FK_FBD1C527C54C8C93');
        $this->addSql('DROP TABLE formation');
        $this->addSql('DROP TABLE formation_audit');
        $this->addSql('DROP TABLE formation_slot');
        $this->addSql('DROP TABLE formation_slot_audit');
    }
}
