<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261006094139 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Bâtiments : types (contenu de jeu réglable) et niveaux par planète';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE building_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description TEXT DEFAULT NULL, base_cost_metal DOUBLE PRECISION NOT NULL, base_cost_crystal DOUBLE PRECISION NOT NULL, base_cost_deuterium DOUBLE PRECISION NOT NULL, cost_factor DOUBLE PRECISION NOT NULL, effect_base DOUBLE PRECISION NOT NULL, effect_growth DOUBLE PRECISION NOT NULL, energy_consumption DOUBLE PRECISION NOT NULL, deuterium_consumption DOUBLE PRECISION NOT NULL, temperature_base DOUBLE PRECISION NOT NULL, temperature_coefficient DOUBLE PRECISION NOT NULL, sort_order INT NOT NULL, code VARCHAR(40) NOT NULL, name VARCHAR(60) NOT NULL, effect VARCHAR(30) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX building_type_code_unique ON building_type (code)');
        $this->addSql('CREATE TABLE building_type_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, extra_data JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_68de65584208405df4b94acf036651c4_idx ON building_type_audit (type)');
        $this->addSql('CREATE INDEX object_id_68de65584208405df4b94acf036651c4_idx ON building_type_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_68de65584208405df4b94acf036651c4_idx ON building_type_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_68de65584208405df4b94acf036651c4_idx ON building_type_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_68de65584208405df4b94acf036651c4_idx ON building_type_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_68de65584208405df4b94acf036651c4_idx ON building_type_audit (created_at)');
        $this->addSql('CREATE TABLE planet_building (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, level INT NOT NULL, planet_id INT NOT NULL, type_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX planet_building_unique ON planet_building (planet_id, type_id)');
        $this->addSql('CREATE INDEX IDX_92265400A25E9820 ON planet_building (planet_id)');
        $this->addSql('CREATE INDEX IDX_92265400C54C8C93 ON planet_building (type_id)');
        $this->addSql('CREATE TABLE planet_building_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, extra_data JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_3b48e844373e41246bb9ccbeb28c5807_idx ON planet_building_audit (type)');
        $this->addSql('CREATE INDEX object_id_3b48e844373e41246bb9ccbeb28c5807_idx ON planet_building_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_3b48e844373e41246bb9ccbeb28c5807_idx ON planet_building_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_3b48e844373e41246bb9ccbeb28c5807_idx ON planet_building_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_3b48e844373e41246bb9ccbeb28c5807_idx ON planet_building_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_3b48e844373e41246bb9ccbeb28c5807_idx ON planet_building_audit (created_at)');
        $this->addSql('ALTER TABLE planet_building ADD CONSTRAINT FK_92265400A25E9820 FOREIGN KEY (planet_id) REFERENCES planet (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE planet_building ADD CONSTRAINT FK_92265400C54C8C93 FOREIGN KEY (type_id) REFERENCES building_type (id) NOT DEFERRABLE');
        // Types de départ (§4.3), paramètres repris des OGame-like classiques, réglables ensuite dans le panneau
        $this->addSql('INSERT INTO building_type (code, name, effect, base_cost_metal, base_cost_crystal, base_cost_deuterium, cost_factor, effect_base, effect_growth, energy_consumption, deuterium_consumption, temperature_base, temperature_coefficient, sort_order, description) VALUES (\'metal_mine\', \'Mine de métal\', \'metal_production\', 60, 15, 0, 1.5, 30, 1.1, 10, 0, 1, 0, 10, \'Extrait le métal du sol de la planète. Plus productive sur les orbites centrales du système.\')');
        $this->addSql('INSERT INTO building_type (code, name, effect, base_cost_metal, base_cost_crystal, base_cost_deuterium, cost_factor, effect_base, effect_growth, energy_consumption, deuterium_consumption, temperature_base, temperature_coefficient, sort_order, description) VALUES (\'crystal_mine\', \'Mine de cristal\', \'crystal_production\', 48, 24, 0, 1.6, 20, 1.1, 10, 0, 1, 0, 20, \'Extrait le cristal. Plus productive sur les orbites proches de l\'\'étoile.\')');
        $this->addSql('INSERT INTO building_type (code, name, effect, base_cost_metal, base_cost_crystal, base_cost_deuterium, cost_factor, effect_base, effect_growth, energy_consumption, deuterium_consumption, temperature_base, temperature_coefficient, sort_order, description) VALUES (\'deuterium_synthesizer\', \'Synthétiseur de deutérium\', \'deuterium_production\', 225, 75, 0, 1.5, 10, 1.1, 20, 0, 1.44, -0.004, 30, \'Isole le deutérium de l\'\'eau de la planète. Plus productif sur les planètes froides.\')');
        $this->addSql('INSERT INTO building_type (code, name, effect, base_cost_metal, base_cost_crystal, base_cost_deuterium, cost_factor, effect_base, effect_growth, energy_consumption, deuterium_consumption, temperature_base, temperature_coefficient, sort_order, description) VALUES (\'solar_plant\', \'Centrale solaire\', \'solar_energy\', 75, 30, 0, 1.5, 20, 1.1, 0, 0, 1, 0.002, 40, \'Produit l\'\'énergie des mines. Plus efficace sur les planètes chaudes.\')');
        $this->addSql('INSERT INTO building_type (code, name, effect, base_cost_metal, base_cost_crystal, base_cost_deuterium, cost_factor, effect_base, effect_growth, energy_consumption, deuterium_consumption, temperature_base, temperature_coefficient, sort_order, description) VALUES (\'fusion_reactor\', \'Centrale à fusion\', \'fusion_energy\', 900, 360, 180, 1.8, 30, 1.05, 0, 10, 1, 0, 50, \'Produit de l\'\'énergie en consommant du deutérium.\')');
        $this->addSql('INSERT INTO building_type (code, name, effect, base_cost_metal, base_cost_crystal, base_cost_deuterium, cost_factor, effect_base, effect_growth, energy_consumption, deuterium_consumption, temperature_base, temperature_coefficient, sort_order, description) VALUES (\'metal_storage\', \'Dépôt de métal\', \'metal_storage\', 1000, 0, 0, 2, 5000, 1, 0, 0, 1, 0, 60, \'Augmente la capacité de stockage du métal ; au-delà, la production est perdue.\')');
        $this->addSql('INSERT INTO building_type (code, name, effect, base_cost_metal, base_cost_crystal, base_cost_deuterium, cost_factor, effect_base, effect_growth, energy_consumption, deuterium_consumption, temperature_base, temperature_coefficient, sort_order, description) VALUES (\'crystal_storage\', \'Dépôt de cristal\', \'crystal_storage\', 1000, 500, 0, 2, 5000, 1, 0, 0, 1, 0, 70, \'Augmente la capacité de stockage du cristal ; au-delà, la production est perdue.\')');
        $this->addSql('INSERT INTO building_type (code, name, effect, base_cost_metal, base_cost_crystal, base_cost_deuterium, cost_factor, effect_base, effect_growth, energy_consumption, deuterium_consumption, temperature_base, temperature_coefficient, sort_order, description) VALUES (\'deuterium_storage\', \'Dépôt de deutérium\', \'deuterium_storage\', 1000, 1000, 0, 2, 5000, 1, 0, 0, 1, 0, 80, \'Augmente la capacité de stockage du deutérium ; au-delà, la production est perdue.\')');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE planet_building DROP CONSTRAINT FK_92265400A25E9820');
        $this->addSql('ALTER TABLE planet_building DROP CONSTRAINT FK_92265400C54C8C93');
        $this->addSql('DROP TABLE building_type');
        $this->addSql('DROP TABLE building_type_audit');
        $this->addSql('DROP TABLE planet_building');
        $this->addSql('DROP TABLE planet_building_audit');
    }
}
